const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      categiry: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 0,
      description: "Camisa popular",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      categiry: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.2,
      numReviews: 10,
      countInStock: 12,
      description: "Camisa popular",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      categiry: "Shirts",
      image: "/images/shirt3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 3,
      countInStock: 25,
      description: "Camisa popular",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      categiry: "pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Caças de design inteligente",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      categiry: "pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "Caças pupulares",
    },
  ],
};

export default data;
